site_name: Fixes & Hacks
nav:
  - Home: index.md
  - Drupal:
      - Setup: drupal/setup.md
      - Multisite: drupal/multisite.md
      - Core Upgrade: drupal/upgrade.md
      - Dependency Injection: drupal/dependency-injection.md
      - Drush Commands: drupal/drush-commands.md
      - Misc Tips: drupal/misc-tips.md
      - Code Snippets: drupal/code-snippets.md
  - Angular:
      - Dummy Server: angular/dummy-server.md
  - Git:
      - Commands: git/commands.md
      - Common Issues: git/common-issues.md
  - jQuery:
      - Upgrade Issues: jquery/upgrade-issues.md
  - Linux & Mac:
      - Commands: linux-mac/commands.md
      - Deployment: linux-mac/deployment.md
  - Misc & Tools:
      - Composer: tools/composer.md
      - VS Code: tools/vscode.md
      - Google Sheets: tools/google-sheets.md
      - Node: tools/logging-with-node.md
      - Regex: tools/regex.md
